// generated by slopgate init — review roots + add project rule packs (see convention-sources.json).
// slopgate project config. Engine is global+auto-latest; THIS file is pinned per project.
export default {
  roots: ["apps/cli/src","apps/ui/src","apps/worker/src","packages/shared/src"],
  exts: [".ts",".tsx",".astro"],
  skipDirs: ["node_modules","dist","tests",".worktrees"],

  // baseline packs this project OPTS INTO (nothing fires until listed)
  baseline: ['no-stubs', 'ts-suppress', 'as-any', 'raw-hex'],

  ux: {
    cls: 'high', // §13 <img>/<video>/<iframe> without width/height → layout shift
  },

  // project-owned rule packs (pinned, in this repo)
  rules: ['./rules/vibeflare-patterns.mjs'],
  astRules: './rules/ast',        // dir of *.yml (optional)
  astDisable: [],                 // ast rule ids to silence in this project

  // commit-tier checkers (detected at init; false/absent = off)
  checkers: {
    'diff-shape': {"maxDirs":5},
  },

  gate: { file: ['critical', 'high'], staged: ['critical', 'high'] },
  suppressions: './suppressions.json',
  fixtures: './fixtures',
};
