#!/usr/bin/env python3
"""Build small runtime derivatives from the user's original logo PNGs.
Requires Pillow for maintenance only; app/runtime have no new dependencies.
Never overwrite sources. Runtime assets and dot geometry are checked into Git.
"""
from pathlib import Path
from PIL import Image, ImageOps
import hashlib, json

ROOT = Path(__file__).resolve().parents[1]
SOURCES = ROOT / 'docs/design/logo'
PUBLIC = ROOT / 'apps/ui/public'
OUT = PUBLIC / 'assets/brand'
OUT.mkdir(parents=True, exist_ok=True)
PALETTE = ['#9d1536', '#ca1d30', '#e73522', '#f64b16', '#ff6914', '#ff9018', '#ffb41d', '#ffdb27']
COLORS = [tuple(int(color[i:i+2], 16) for i in (1, 3, 5)) for color in PALETTE]
sha = lambda path: hashlib.sha256(path.read_bytes()).hexdigest()
files = sorted(SOURCES.glob('*.png'))
assert len(files) == 9, 'Expect all nine user-provided originals.'
wordmark = next(p for p in files if p.name.endswith('(3).png'))
symbol = next(p for p in files if p.name.endswith('(9).png'))


def crop(path):
    image = Image.open(path).convert('RGBA')
    mask = image.getchannel('A').point(lambda value: 255 if value >= 16 else 0)
    bbox = mask.getbbox()
    assert bbox
    image.putalpha(image.getchannel('A').point(lambda value: value if value >= 16 else 0))
    return image.crop(bbox), bbox

mark, mark_bounds = crop(symbol)
word, word_bounds = crop(wordmark)
outputs = []

def record(path, source, operation):
    image = Image.open(path)
    outputs.append({'file':str(path.relative_to(PUBLIC)), 'source':source.name, 'operation':operation,
                    'width':image.width, 'height':image.height, 'bytes':path.stat().st_size, 'sha256':sha(path)})

for width in (320, 640):
    height = round(width * word.height / word.width)
    path = OUT / f'vibeflare-wordmark-{width}.webp'
    word.resize((width, height), Image.Resampling.LANCZOS).save(path, 'WEBP', quality=92, method=6, exact=True)
    record(path, wordmark, 'Trim transparent margin using alpha >=16; resize, preserve transparency.')
path = OUT / 'vibeflare-mark.webp'
ImageOps.contain(mark, (128, 128), Image.Resampling.LANCZOS).save(path, 'WEBP', quality=92, method=6, exact=True)
record(path, symbol, 'Trim transparent margin and contain in 128px; preserve transparency.')
for size, name in [(32, 'favicon-32.png'), (64, 'favicon-64.png'), (180, 'apple-touch-icon.png'), (192, 'icon-192.png')]:
    icon = Image.new('RGBA', (size, size), (0,0,0,0))
    inner = ImageOps.contain(mark, (round(size*.90), round(size*.90)), Image.Resampling.LANCZOS)
    icon.alpha_composite(inner, ((size-inner.width)//2, (size-inner.height)//2))
    path = PUBLIC / name
    icon.save(path, optimize=True)
    record(path, symbol, 'Center transparent mark in square canvas with 5% padding.')

# Sample the actual symbol, preserving its aspect ratio rather than redrawing it.
logo = ImageOps.contain(mark, (422, 270), Image.Resampling.LANCZOS)
stage = Image.new('RGBA', (504, 316), (0,0,0,0))
stage.alpha_composite(logo, ((504-logo.width)//2, (316-logo.height)//2))
rows = []
count = 0
for y in range(44):
    row = ''
    for x in range(70):
        red, green, blue, alpha = stage.getpixel((7+x*7, 7+y*7))
        if alpha < 128:
            row += '.'
        else:
            index = min(range(len(COLORS)), key=lambda i: sum((a-b)**2 for a,b in zip((red,green,blue),COLORS[i])))
            row += str(index); count += 1
    rows.append(row)
data = ROOT / 'apps/ui/src/lib/flare-logo-data.ts'
data.write_text('/** Generated by tools/build-logo-assets.py from the supplied transparent VF mark. */\n'
    + f"export const FLARE_LOGO_SOURCE_SHA = '{sha(symbol)}';\n"
    + f'export const FLARE_MARKED_COUNT = {count};\n'
    + 'export const FLARE_ROWS = [\n' + ''.join(f"  '{row}',\n" for row in rows) + '] as const;\n')
manifest = {
    'schemaVersion':1, 'source':'User-supplied VibeFlare logo pack, 2026-09-13',
    'originals':[{'file':p.name, 'bytes':p.stat().st_size, 'sha256':sha(p), 'dimensions':list(Image.open(p).size)} for p in files],
    'selected':{'wordmark':wordmark.name, 'symbol':symbol.name, 'wordmarkCrop':word_bounds, 'symbolCrop':mark_bounds},
    'runtime':outputs,
    'dotField':{'source':symbol.name, 'sourceSha256':sha(symbol), 'markedDots':count, 'totalDots':3080,
                'generatedFile':str(data.relative_to(ROOT)), 'generatedSha256':sha(data)},
}
(SOURCES/'manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
print(f'Preserved {len(files)} originals. Generated {len(outputs)} assets ({sum(x["bytes"] for x in outputs):,} bytes total), {count} logo dots.')
